### ISSUE TITLE
Gen3 Lite - All joints publishing 0.0

### ISSUE THREAD

**Issue by civerachb-cpr** [Kinovarobotics/ros_kortex#127]
I'm trying to mount a Gen3 Lite onto a mobile robot platform. I've added the arm to the robot's URDF, and the driver appears to be launching without any errors.  But when I echo the joint states all joints (except the fingers) report 0.0 for their position, regardless of how the arm is physically oriented.

Output of launching the driver:

started roslaunch server http://cpr-dingo-nano:36175/

```
SUMMARY
========

PARAMETERS
 * /arm/arm_driver/api_connection_inactivity_timeout_ms: 20000
 * /arm/arm_driver/api_rpc_timeout_ms: 2000
 * /arm/arm_driver/api_session_inactivity_timeout_ms: 35000
 * /arm/arm_driver/arm: gen3_lite
 * /arm/arm_driver/cyclic_data_publish_rate: 40
 * /arm/arm_driver/default_goal_time_tolerance: 0.5
 * /arm/arm_driver/default_goal_tolerance: 0.005
 * /arm/arm_driver/dof: 6
 * /arm/arm_driver/gripper: gen3_lite_2f
 * /arm/arm_driver/gripper_joint_limits_max: [-0.09]
 * /arm/arm_driver/gripper_joint_limits_min: [0.96]
 * /arm/arm_driver/gripper_joint_names: ['arm_right_finge...
 * /arm/arm_driver/ip_address: 192.168.1.10
 * /arm/arm_driver/joint_names: ['arm_joint_1', '...
 * /arm/arm_driver/maximum_accelerations: [1.0, 0.5, 0.4, 1...
 * /arm/arm_driver/maximum_velocities: [0.5, 0.5, 0.5, 0...
 * /arm/arm_driver/password: admin
 * /arm/arm_driver/prefix: arm_
 * /arm/arm_driver/robot_name: arm
 * /arm/arm_driver/sim: False
 * /arm/arm_driver/use_hard_limits: False
 * /arm/arm_driver/username: admin
 * /arm/hztest_test_base_feedback/hz: 40
 * /arm/hztest_test_base_feedback/hzerror: 5.0
 * /arm/hztest_test_base_feedback/test_duration: 30.0
 * /arm/hztest_test_base_feedback/topic: base_feedback
 * /arm/hztest_test_base_feedback/wait_time: 10.0
 * /arm/hztest_test_driver_joint_state/hz: 40
 * /arm/hztest_test_driver_joint_state/hzerror: 5.0
 * /arm/hztest_test_driver_joint_state/test_duration: 30.0
 * /arm/hztest_test_driver_joint_state/topic: base_feedback/joi...
 * /arm/hztest_test_driver_joint_state/wait_time: 10.0
 * /arm/hztest_test_joint_state_publisher_joint_states/hz: 40
 * /arm/hztest_test_joint_state_publisher_joint_states/hzerror: 5.0
 * /arm/hztest_test_joint_state_publisher_joint_states/test_duration: 30.0
 * /arm/hztest_test_joint_state_publisher_joint_states/topic: joint_states
 * /arm/hztest_test_joint_state_publisher_joint_states/wait_time: 10.0
 * /arm/joint_state_publisher/rate: 40
 * /arm/joint_state_publisher/source_list: ['base_feedback/j...
 * /arm/joint_state_publisher/use_gui: False
 * /arm/kortex_driver_tests/api_connection_inactivity_timeout_ms: 20000
 * /arm/kortex_driver_tests/api_rpc_timeout_ms: 2000
 * /arm/kortex_driver_tests/api_session_inactivity_timeout_ms: 35000
 * /arm/kortex_driver_tests/arm: gen3_lite
 * /arm/kortex_driver_tests/cyclic_data_publish_rate: 40
 * /arm/kortex_driver_tests/default_goal_time_tolerance: 0.5
 * /arm/kortex_driver_tests/default_goal_tolerance: 0.005
 * /arm/kortex_driver_tests/dof: 6
 * /arm/kortex_driver_tests/gripper: gen3_lite_2f
 * /arm/kortex_driver_tests/gripper_joint_limits_max: [-0.09]
 * /arm/kortex_driver_tests/gripper_joint_limits_min: [0.96]
 * /arm/kortex_driver_tests/gripper_joint_names: ['arm_right_finge...
 * /arm/kortex_driver_tests/ip_address: 192.168.1.10
 * /arm/kortex_driver_tests/joint_names: ['arm_joint_1', '...
 * /arm/kortex_driver_tests/maximum_accelerations: [1.0, 0.5, 0.4, 1...
 * /arm/kortex_driver_tests/maximum_velocities: [0.5, 0.5, 0.5, 0...
 * /arm/publish_test_kortex_driver/topics: [{'name': '/arm/b...
 * /rosdistro: melodic
 * /rosversion: 1.14.9

NODES
  /arm/
    arm_driver (kortex_driver/kortex_arm_driver)
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/robot_state_publisher)

ROS_MASTER_URI=http://localhost:11311

process[arm/arm_driver-1]: started with pid [19233]
process[arm/joint_state_publisher-2]: started with pid [19234]
process[arm/robot_state_publisher-3]: started with pid [19235]
[ WARN] [1603303485.136751012]: The root link arm_base_link has an inertia specified in the URDF, but KDL does not support a root link with an inertia.  As a workaround, you can add an extra dummy link to your URDF.
[ INFO] [1603303485.762735895]: Session created successfully for TCP services
[ INFO] [1603303485.772901267]: Session created successfully for UDP services
[ INFO] [1603303485.782607917]: -------------------------------------------------
[ INFO] [1603303485.782719433]: Scanning all devices in robot... 
[ INFO] [1603303485.807014394]: Base device was found on device identifier 0
[ INFO] [1603303485.808454990]: Actuator device of type SMALL_ACTUATOR was found on device identifier 7
[ INFO] [1603303485.808566350]: Actuator device of type SMALL_ACTUATOR was found on device identifier 5
[ INFO] [1603303485.808614269]: Actuator device of type MEDIUM_ACTUATOR was found on device identifier 1
[ INFO] [1603303485.808665938]: Actuator device of type BIG_ACTUATOR was found on device identifier 2
[ INFO] [1603303485.808708024]: Actuator device of type MEDIUM_ACTUATOR was found on device identifier 3
[ INFO] [1603303485.808758443]: Actuator device of type SMALL_ACTUATOR was found on device identifier 4
[ INFO] [1603303485.808799279]: -------------------------------------------------
[ INFO] [1603303485.879463733]: State changed from INITIALIZING to IDLE

[ INFO] [1603303485.900031573]: -------------------------------------------------
[ INFO] [1603303485.900223198]: Initializing Kortex Driver's services...
[ INFO] [1603303488.253699341]: Kortex Driver's services initialized correctly.
[ INFO] [1603303488.253829296]: -------------------------------------------------
[ INFO] [1603303488.257125407]: The Kortex driver has been initialized correctly!
```

Output of echoing the joint state:

```
rostopic echo /arm/joint_states  -n 5
header: 
  seq: 14199
  stamp: 
    secs: 1603303902
    nsecs: 118694067
  frame_id: ''
name: [arm_joint_1, arm_joint_2, arm_joint_3, arm_joint_4, arm_joint_5, arm_joint_6, arm_right_finger_bottom_joint,
  arm_right_finger_tip_joint, arm_left_finger_bottom_joint, arm_left_finger_tip_joint]
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.149, 0.0, 0.149]
velocity: []
effort: []
---
header: 
  seq: 14200
  stamp: 
    secs: 1603303902
    nsecs: 143697977
  frame_id: ''
name: [arm_joint_1, arm_joint_2, arm_joint_3, arm_joint_4, arm_joint_5, arm_joint_6, arm_right_finger_bottom_joint,
  arm_right_finger_tip_joint, arm_left_finger_bottom_joint, arm_left_finger_tip_joint]
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.149, 0.0, 0.149]
velocity: []
effort: []
---
header: 
  seq: 14201
  stamp: 
    secs: 1603303902
    nsecs: 168684005
  frame_id: ''
name: [arm_joint_1, arm_joint_2, arm_joint_3, arm_joint_4, arm_joint_5, arm_joint_6, arm_right_finger_bottom_joint,
  arm_right_finger_tip_joint, arm_left_finger_bottom_joint, arm_left_finger_tip_joint]
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.149, 0.0, 0.149]
velocity: []
effort: []
---
header: 
  seq: 14202
  stamp: 
    secs: 1603303902
    nsecs: 193634033
  frame_id: ''
name: [arm_joint_1, arm_joint_2, arm_joint_3, arm_joint_4, arm_joint_5, arm_joint_6, arm_right_finger_bottom_joint,
  arm_right_finger_tip_joint, arm_left_finger_bottom_joint, arm_left_finger_tip_joint]
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.149, 0.0, 0.149]
velocity: []
effort: []
---
header: 
  seq: 14203
  stamp: 
    secs: 1603303902
    nsecs: 218625068
  frame_id: ''
name: [arm_joint_1, arm_joint_2, arm_joint_3, arm_joint_4, arm_joint_5, arm_joint_6, arm_right_finger_bottom_joint,
  arm_right_finger_tip_joint, arm_left_finger_bottom_joint, arm_left_finger_tip_joint]
position: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.149, 0.0, 0.149]
velocity: []
effort: []
---
```

In rviz I can see the robot's arm sticking straight up in the air, despite it being curled up in the stowed position on the physical robot.

I can't see any errors that would be preventing the arm from working, but maybe I'm missing something?  I've updated the arm's firmware to the latest version & rebuilt the driver a few times, but still no luck.

EDIT: fixed the code formatting.
