### ISSUE TITLE
send_gripper_command is interupted by /my_gen3/in/joint_velocity topic

### ISSUE THREAD

**Issue by AlfaKeNTAvR** [Kinovarobotics/ros_kortex#325]
## Description

Kinova Gen3 (firmware 2.5.2) gripper stops any movement initiated by send_gripper_command service call if publishing to /my_gen3/in/joint_velocity topic. Depending on the publishing rate the gripper might start some motion: almost closes on rate 1Hz, twitches a bit on >10Hz.

## Version

ROS distribution : 

Branch and commit you are using : noetic-devel 085b694280a77eb7be14ff2af86958ba18b633cf

## Steps to reproduce

```
roslaunch kortex_driver kortex_driver.launch ip_address:=192.168.1.12 start_rviz:=false start_moveit:=false gripper:=robotiq_2f_85 robot_name:="my_gen3"

rostopic pub -r 10 my_gen3/in/joint_velocity kortex_driver/Base_JointSpeeds "joint_speeds:
- joint_identifier: 0
  value: 0.0
  duration: 0
duration: 0" 

rosservice call /my_gen3/base/send_gripper_command "input:
  mode: 3
  gripper:
    finger:
    - finger_identifier: 0
      value: 0.0
  duration: 0"

rosservice call /my_gen3/base/send_gripper_command "input:
  mode: 3
  gripper:
    finger:
    - finger_identifier: 0
      value: 1.0
  duration: 0" 
```

## Code example (if necessary)

```
    # paste code here #
```

## Expected behavior

On another Kinova Gen3 (older) which runs 2.3.0 firmware the behavior is as expected. Publish to the topic does not have any effect on the gripper service call. I have tested with both arms, same ros_kortex, just changed the IP in the terminal.

## Any other information

Kinova Gen3 (older) firmware 2.3.0 - works as expected.
Kinova Gen3 (purchased Summer 2023) firmware 2.4.0 - 2.5.2 does not work.

Maybe it is related to the ros_kortex version? It seems to work on my colleagues PC, I think he uses older ros_kortex version, but then it shouldn't work with the older Kinova too in my system.
